# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: CI

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: macos-15

    timeout-minutes: 8
    
    steps:
    - uses: actions/checkout@v4

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_16.2.app
      
    - name: Xcode version
      run: /usr/bin/xcodebuild -version
      
    - name: Create Secrets.xcconfig
        run: |
            echo "API_KEY=${{ secrets.API_KEY }}" > TheMovieDatabaseiOS/Secrets.xcconfig
            echo "BASE_URL_STRING=${{ secrets.BASE_URL_STRING }}" >> TheMovieDatabaseiOS/Secrets.xcconfig

      
    - name: Build and Test
      env:
        API_KEY: ${{ secrets.API_KEY }}
        BASE_URL_STRING: ${{ secrets.BASE_URL_STRING }}
      run: |
        xcodebuild clean build test \
            -project TMDB.xcodeproj \
            -scheme "CI" \
            -sdk macosx \
            -destination "platform=macOS" \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            ONLY_ACTIVE_ARCH=YES
